import Head from "next/head";
import React from "react";

const MainProfile = () => {
  return (
    <div className="main-container">
      <Head>
        <title>AzriClone || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default MainProfile;
