import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import { wrapper } from "../../app/store";
import WelcomeSection from "../../components/HomePage/WelcomeSection";
import { FriendType } from "../../typing.d";

interface Props {
  mainProfile: FriendType;
}
const MainProfile = ({ mainProfile }: Props) => {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!session) {
      router.push("/");
    }
  }, []);

  return (
    <div className="main-container">
      <Head>
        <title>AzriClone || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default MainProfile;

export const getStaticProps = wrapper.getStaticProps((store) => async () => {
  let mainProfile: FriendType = store.getState().friend.mainProfile;

  return {
    props: { mainProfile },
  };
});
